export const TICK_RATE = 60;
export const FIXED_TIMESTEP_SECONDS = 1 / TICK_RATE;

export const TANK_RESPAWN_DELAY_MS = 3000;
export const TANK_RESPAWN_PROTECTION_MS = 1800;
export const SPAWN_CORNER_PADDING = 56;

export const SHOT_PREVIEW_BULLET_RADIUS = 5;
export const SHOT_PREVIEW_REFLECTIONS = 1;
export const SHOT_PREVIEW_MAX_DISTANCE = 720;

export const BULLET_EXPLOSION_VISUAL_DURATION_MS = 160;

export const DEFAULT_CHARGED_SHOT_MIN_HOLD_MS = 150;
export const DEFAULT_CHARGED_SHOT_MAX_HOLD_MS = 1200;
export const DEFAULT_CHARGED_SHOT_OVERCHARGE_MS = 2400;

export const MINE_EXPLOSION_RADIUS = 118;
export const MINE_EXPLOSION_VISUAL_DURATION_MS = 210;

export const DEFAULT_WORLD_WIDTH = 3200;
export const DEFAULT_WORLD_HEIGHT = 2133;
